"""empty message

Revision ID: 659f0d8e896b
Revises: 
Create Date: 2023-07-03 11:54:00.610472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659f0d8e896b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soc_user',
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('pswd', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('login')
    )
    op.create_table('post',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['soc_user.login'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('reaction',
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('post', sa.Integer(), nullable=False),
    sa.Column('likee', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['likee'], ['soc_user.login'], ),
    sa.ForeignKeyConstraint(['post'], ['post.id_'], ),
    sa.PrimaryKeyConstraint('post', 'likee')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reaction')
    op.drop_table('post')
    op.drop_table('soc_user')
    # ### end Alembic commands ###
